CREATE DATABASE COFFEESHOP
GO
USE COFFEESHOP



CREATE TABLE NHANVIEN (
    MANV INT PRIMARY KEY,
    HOTEN NVARCHAR(200),
    NGAYSINH DATE,
    SDT VARCHAR(15),
    DIACHI NVARCHAR(200),
    GIOITINH NVARCHAR(3) CHECK (GIOITINH IN ('Nam', 'Nữ')),
	TENVT NVARCHAR(100),
	TENDN VARCHAR(50) UNIQUE ,
    MATKHAU VARCHAR(50)
);

CREATE TABLE LOAIMON (
    MALOAI INT PRIMARY KEY,
    TENLOAI NVARCHAR(100)
);

CREATE TABLE MENU (
    MAMA INT PRIMARY KEY,
    MALOAI INT,
    TENMONAN NVARCHAR(200),
    GIA DECIMAL(7),
    FOREIGN KEY (MALOAI) REFERENCES LOAIMON(MALOAI)
);

CREATE TABLE KHACHHANG (
    MAKH INT PRIMARY KEY,
    HOTEN NVARCHAR(200)
);

CREATE TABLE HOADON (
    MAHD INT PRIMARY KEY,
    MANV  INT,
    MAKH  INT,
    NGAYLAP DATE,
	GIA DECIMAL(10),
    TINHTRANG VARCHAR(20),
    FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV),
    FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);

CREATE TABLE CHITIETHOADON (
    MAHD INT,
    MAMA INT,
    SOLUONG INT,
    PRIMARY KEY (MAHD, MAMA),
    FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD),
    FOREIGN KEY (MAMA) REFERENCES MENU(MAMA)
);

INSERT INTO LOAIMON VALUES ('1', 'Coffee');
INSERT INTO MENU VALUES ('1', '1', 'Cafe đen', '12000');
SELECT * FROM MENU;