CREATE DATABASE COFFEESHOP
GO
USE COFFEESHOP



CREATE TABLE EMPLOYEE (
    ID_EM INT PRIMARY KEY,
	IMAGE_DATA IMAGE,
    NAME_EM NVARCHAR(4000),
    DAY_OF_BIRTH DATE,
    PHONE_NUM VARCHAR(15),
    ADDRESS_EM NVARCHAR(4000),
    SEX NVARCHAR(3) CHECK (SEX IN ('Nam', N'Nữ')),
	NAME_ROLE NVARCHAR(100),
	USERNAME VARCHAR(50) UNIQUE ,
    PASS VARCHAR(50)
);
CREATE TABLE TYPE (
    ID INT PRIMARY KEY,
	TYPE NVARCHAR(100),
	AVAILABLE BIT
);
CREATE TABLE MENU (
    ID INT PRIMARY KEY,
	IMAGE_DATA IMAGE,
	ID_TYPE INT,
    NAME_FOOD NVARCHAR(200),
	DESCRIPTION NVARCHAR(500),
    PRICE DECIMAL(7),
	AVAILABLE BIT,
    FOREIGN KEY (ID_TYPE) REFERENCES TYPE(ID)
);

CREATE TABLE BILL (
    ID_BILL INT PRIMARY KEY,
    ID_EM  INT,
	NAME_CUSTOMER NVARCHAR(200),
    DAY_BILL DATE,
	PRICE DECIMAL(10),
    STATUS_BILL VARCHAR(20),
    FOREIGN KEY (ID_EM) REFERENCES EMPLOYEE(ID_EM)
);
CREATE TABLE BILLDETAIL (
    ID_BILL INT,
    ID INT,
    SOLUONG INT,
    PRIMARY KEY (ID_BILL, ID),
    FOREIGN KEY (ID_BILL) REFERENCES BILL(ID_BILL),
    FOREIGN KEY (ID) REFERENCES MENU(ID)
);


INSERT INTO TYPE VALUES 
('0','COFFEE','1'),
('1','JUICES','1'),
('2','TEA','1'),
('3','SMOOTHIES','1'),
('4','ICE BLENDED','1');


INSERT INTO BILL VALUES
(0, 1, N'Customer A', '2023-01-05', 150000, 'Pending'),
(1, 1, N'Customer B', '2023-02-10', 120000, 'Pending');

INSERT INTO BILLDETAIL VALUES
(0, 0, 2),
(0, 1, 1),
(1, 2, 3),
(1, 4, 1),
(1, 5, 2);